<div id="card-howto" class="card-wrapper card-center"><div class="card">
    <h2>How To Order</h2>
    <ul class="order-menu">
        <?php /** @noinspection PhpUndefinedVariableInspection */
        foreach($videos as $video) { ?>
        <li><a href="#card-<?= $video->id ?>"><span><?= $video->text ?></span></a></li>
        <?php } ?>
    </ul>
</div></div>

<?php foreach($videos as $video) { ?>
<div id="card-<?= $video->id ?>" class="card-wrapper card-autoexpand"><div class="card">
        <div class="text-holder"><a class="arrow-back" href="#card-howto">  <img src="resources/sprites/chevron-circle-left.svg" /></a><h3><?= $video->text ?></h3></div>
        <div class="video-holder"><video autoplay muted playsinline loop src="video/<?= $video->file ?>"></video></div>
    </div></div>
<?php } ?>
