<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width">
    <title>How to order - Hand Me A Coffee</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="resources/app.css" />
</head>
<body class="spa">
<div class="header">
    <div class="logo"><img class="logo-img" src="resources/logo.svg" /><h1>Hand Me A Coffee</h1></div>
    <ul class="header-menu">
        <li<?php if($activePage == 'about') { echo ' class="active"'; } ?>><a href="about.html">About</a></li>
        <li<?php if($activePage == 'howtoorder') { echo ' class="active"'; } ?>><a href="how-to-order.html">How To Order</a></li>
        <li<?php if($activePage == 'getinvolved') { echo ' class="active"'; } ?>><a href="get-involved.html">Get Involved</a></li>
    </ul>
</div>
<div id="content-<?= $activePage ?>" class="content">
    <?= /** @noinspection PhpUndefinedVariableInspection */
    $pageContent ?>
</div>
<script type="application/javascript" src="resources/app.js"></script>
</body>
</html>

